### PR TITLE
Revert "CompatHelper: bump compat for Bijectors to 0.13, (keep existing compat)"

### PR DESCRIPTION
**Pull request by giordano**
Reverts JuliaAstro/Transits.jl#41

### CODE REVIEW

**Comment by giordano** [comment]
@abhro it'd be better to make sure tests actually pass instead of blindly merging broken PRs

**Comment by abhro** [comment]
Thanks for the fix! Sorry I messed that up 😞 . Is there a way to trigger CI on CompatHelper PRs?

**Comment by giordano** [comment]
Close and reopen the PR, or update it (e.g. rebase on the target branch, if possible)

**Comment by abhro** [comment]
Alright. Thank you!!! Again, sorry for the blunder!

**Pull request merged**
