### PR TITLE
Switch to `InverseFunctions.inverse`

### PR DESCRIPTION
**Pull request by icweaver**
Just following up from here https://github.com/TuringLang/Bijectors.jl/pull/212

### CODE REVIEW

**Comment by mileslucas** [comment]
Thanks, Ian! The changes look good, I just want to check something-

@oschulz do we need to change the definition here to use `InverseFunctions` instead of `Bijectors.Inverse`? https://github.com/JuliaAstro/Transits.jl/blob/16fc5c91b01c5474da32a37fa6053258bca929a6/src/distributions.jl#L58

**Comment by oschulz** [comment]
> @oschulz should we change the definition here to use InverseFunctions instead of Bijectors.Inverse

No, I think it can stay as it is. `InverseFunctions.inverse` only provides an abstract API but no implementations of inverses that you could specialize on (except for `InverseFunctions.square`). So for the inverse transform, you can either create an explicit struct `InverseKipping13Transform` or use `Inverse{<:Kipping13Transform}`, or ...

If you implement both the InverseFunctions.jl and ChangesOfVariables.jl API, you may be able to not depend on Bijectors.jl at all, though.

**Comment by mileslucas** [comment]
> If you implement both the InverseFunctions.jl and ChangesOfVariables.jl API, you may be able to not depend on Bijectors.jl at all, though.

Sounds like that's worth trying in a future PR!

Thanks for the comments Oliver, and thanks for the contribution Ian!

**Comment by icweaver** [comment]
Sounds good!

Sort of a bookkeeping question, but is there a preference on how we want keep tabs on things like this? I just [added it as a discussion](https://github.com/JuliaAstro/Transits.jl/discussions/35), but maybe it would be better to track as a `one day` issue or something instead?

**Comment by mileslucas** [comment]
For bookkeeping I have a "rent-free" unit in the back of my head 😂

I think discussion is a good spot for planning contributions, so that's appropriate, then it can move to a PR when someone finds the time.

**Pull request merged**
